name: Publish

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Refresh Gradle Dependencies
        run: ./gradlew --refresh-dependencies
      - name: Publish
        run: ./gradlew publish
        env:
#          GITHUB_USERNAME: ${{ github.actor }}
#          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
#          BUILD_NUMBER: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}